spring:
  sql:
    init:
      platform: mysql
      mode: always
  datasource:
    username: # place your username here
    password: # place your password here
    driver-class-name: com.mysql.jdbc.Driver

